# Setup
title: Intelligent Petroleum Engineering Lab
description: Intelligent Petroleum Engineering Lab (IPE-lab) is a research lab dedicated to artificial intelligence code development for the petroleum engineering industry
url: https://IPE-lab.github.io
avatar: /avatar.png
paginate: 5
permalink: pretty
cover_image: /bg.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: vszhub
  card: summary
logo: logo.png
social:
  name: IPE-lab
  links:
    - https://twitter.com/vszhub
    - https://github.com/IPE-lab
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: IPE-lab
  url: https://github.com/IPE-lab
  email: xxx
